### ISSUE TITLE
Python 3.4 Support ?

### ISSUE THREAD

**Issue by depado** [asciinema/asciinema#62]
Hi. 
Since I'm using Archlinux I'm always up to date both with Python 3 branch and Python 2 branch.
Here is the recent traceback I got (used the git version)
Traceback (most recent call last):
  File "/usr/bin/asciinema", line 9, in <module>
    load_entry_point('asciinema==0.9.8', 'console_scripts', 'asciinema')()
  File "/usr/lib/python3.4/site-packages/asciinema/**main**.py", line 7, in main
    get_command(sys.argv[1:], Config()).execute()
  File "/usr/lib/python3.4/site-packages/asciinema/commands/record.py", line 24, in execute
    self._upload_asciicast(asciicast)
  File "/usr/lib/python3.4/site-packages/asciinema/commands/record.py", line 46, in _upload_asciicast
    url = self.uploader.upload(self.api_url, self.api_token, asciicast)
  File "/usr/lib/python3.4/site-packages/asciinema/uploader.py", line 29, in upload
    headers=headers)
  File "/usr/lib/python3.4/site-packages/asciinema/requests_http_adapter.py", line 7, in post
    response = requests.post(url, data=fields, files=files, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, *_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 292, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 423, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 238, in _get_conn
    return conn or self._new_conn()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 205, in _new_conn
    strict=self.strict)
TypeError: __init__() got an unexpected keyword argument 'strict'

I don't know if the 'strict' argument is part of some specification or not. 
Is there a way I could work with asciinema with 3.4 ? :)
